# docker images
image:
  modelserver: lightbend/kubeflow-modelserver
  client: lightbend/kubeflow-recommender-data
  pullPolicy: Always
  version: 0.0.1
# Configuration parameters for an application
configuration:
  kafka:
    brokerlist : "strimzi-kafka-brokers.boris.svc.cluster.local:9092"
  minio:
    miniourl: "http://minio-service.kubeflow.svc.cluster.local:9000/"
    miniokey: "minio"
    miniosecret: "minio123"
  recommender:
    defaulturl: "http://recommender.boris.svc.cluster.local:8501"
    alternativeurl: "http://recommender1.boris.svc.cluster.local:8501"
  publisher :
    data_publish_interval : "1 second"
  serving :
    port : 5500
