apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender1
  labels:
    app: recommender1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommender1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recommender1
    spec:
      containers:
        - name: serving
          image: "{{ .Values.image.server }}:{{ .Values.image.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8501
              name: serving
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: serving
            initialDelaySeconds: 15
            timeoutSeconds: 1
          env:
            - name: "AWS_REGION"
              value: "us-west-1"
            - name: "S3_REGION"
              value: "us-west-1"
            - name: "S3_ENDPOINT"
              value: "minio-service.kubeflow.svc.cluster.local:9000"
            - name: "S3_USE_HTTPS"
              value: "0"
            - name: "S3_VERIFY_SSL"
              value: "0"
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom: { secretKeyRef: { name: "minioaccess", key: "AWS_ACCESS_KEY_ID" } }
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom: { secretKeyRef: { name: "minioaccess", key: "AWS_SECRET_ACCESS_KEY" } }
            - name: "MODEL_BASE_PATH"
              value: "s3://models"
            - name: "MODEL_NAME"
              value: "recommender1"
          volumes:
            - name: secret-volume
              secret:
                secretName: minioaccess
---
apiVersion: v1
kind: Service
metadata:
  name: recommender1
spec:
  selector:
    app: recommender1
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501

